name: CI-CD Docker Pipeline

on:
  push:
    branches:
      - main
      - trivy

env:
  IMAGE_NAME: ci-html
  IMAGE_TAG: 1.0.1
  # maman10 = votre username Docker Hub
  DOCKER_REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:

  # ===============================
  # JOB 1 - CI : BUILD + PUSH + SCAN
  # ===============================
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Display variables
        run: |
          echo "IMAGE_NAME: $IMAGE_NAME"
          echo "IMAGE_TAG: $IMAGE_TAG"
          echo "DOCKER_REGISTRY: $DOCKER_REGISTRY"

      # Login avec token PAT (pas mot de passe)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .

      - name: Verify image
        run: |
          docker image ls | grep $IMAGE_NAME

      - name: Push Docker image
        run: |
          docker push $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      # Scan Trivy — pointe sur la vraie image buildée
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: table
          severity: CRITICAL,HIGH
          exit-code: 0
          vuln-type: os,library
          ignore-unfixed: true

  # ===============================
  # JOB 2 - CD : DEPLOY
  # ===============================
  deploy:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Hello deploy
        run: |
          echo "Hello deploy"

      # Login aussi dans deploy pour pouvoir pull
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull latest image
        run: |
          docker pull $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Stop existing container
        run: |
          docker stop ci-app || true

      - name: Remove old container
        run: |
          docker rm ci-app || true

      - name: Run new container
        run: |
          docker run -d \
            -p 80:80 \
            --name ci-app \
            $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Verify container is running
        run: |
          docker ps | grep ci-app
          echo "Deploiement reussi !"
