name: CI-CD Docker Pipeline

on:
  push:
    branches:
      - main
      - trivy

env:
  IMAGE_NAME: html5up-forty
  DOCKER_REGISTRY: maman10

jobs:
  # =============================== 
  # JOB 1 - BUILD, TEST, SCAN & PUSH
  # ===============================
  build-test-scan:
    runs-on: ubuntu-latest
    outputs:
      image-sha: ${{ steps.build-push.outputs.image-sha }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build, test & push image (SHA + latest)
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |

      - name: Test image health
        run: |
          docker run --rm ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest wget --quiet --tries=1 --spider http://localhost/ || exit 1

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          vuln-type: 'os,library'
          ignore-unfixed: true



  # =============================== 
  # JOB 2 - CD : DEPLOY
  # ===============================
  deploy:
    needs: build-test-scan
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull latest image
        run: docker pull ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Stop existing container
        run: docker stop ci-app || true

      - name: Remove old container
        run: docker rm ci-app || true

      - name: Run new container
        run: |
          docker run -d \
            -p 80:80 \
            --name ci-app \
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Verify container is running
        run: |
          docker ps | grep ci-app
          echo "✅ Site disponible sur http://localhost:80"

